# Site settings
title: "unionstars"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://unionstars.github.io" # the base hostname & protocol for your site
github_username: unionstars

timezone: Beijing
plugins: ['jekyll-paginate']

# Build settings
highlighter: rouge
permalink: /:categories/:title/

markdown: kramdown
# markdown: redcarpet
redcarpet:
  extensions: ['fenced_code_blocks', 'tables']

paginate: 25

github: [metadata]
